#!/bin/bash
# This script demonstrates the use of variables in bash some special variables
echo "Script Name: $0"
echo "First Argument: $1"
echo "Second Argument: $2"
echo "Total Number of Arguments: $#"
echo "All Arguments: $*"
echo "Process ID: $$"
echo "Last Command Exit Status: $?"
echo "Last Background Process ID: $!"
echo "Bash Version: $BASH_VERSION"
echo "Home Directory: $HOME"
echo "Current Working Directory: $PWD"
echo "User Name: $USER"
echo "Host Name: $HOSTNAME"
echo "Internal Field Separator: $IFS"
echo "Shell Options: $-"
echo "Array of All Positional Parameters: $@"
echo "Current Shell: $SHELL"
echo "Operating System: $OSTYPE"
echo "Current Date and Time: $(date)"
echo "Current User ID: $UID"
echo "Current Group ID: $GID"
echo "Last Command Run in Background: $!"
echo "Number of Commands in History: $HISTCMD"
echo "Last Command in History: $(history 1)"
echo "Terminal Type: $TERM"
echo "Locale Settings: $LANG"
echo "Path Variable: $PATH"
echo "Prompt String: $PS1"
echo "Random Number: $RANDOM"
echo "Time Zone: $TZ"
echo "Version of the OS: $(uname -a)"
echo "Uptime of the System: $(uptime)"
echo "Memory Usage: $(free -h)"
echo "Disk Usage: $(df -h)"
echo "Network Configuration: $(ifconfig || ip addr)"
echo "List of Running Processes: $(ps aux)"
echo "Environment Variables: $(printenv)"
echo "Shell Level: $SHLVL"
echo "Last Command's Output: $(!!)"
echo "Number of Users Logged In: $(who | wc -l)"
echo "Current Date: $(date +%Y-%m-%d)"
echo "Current Time: $(date +%H:%M:%S)"
echo "Uptime in Seconds: $(cat /proc/uptime | awk '{print $1}')"
echo "Load Average: $(cat /proc/loadavg)"
echo "Number of CPU Cores: $(nproc)"
echo "CPU Information: $(lscpu)"
echo "Block Devices: $(lsblk)"
echo "Mounted Filesystems: $(mount | column -t)"
echo "Active Network Connections: $(netstat -tuln)"
echo "Firewall Status: $(sudo ufw status)"
echo "Scheduled Cron Jobs: $(crontab -l)"
echo "SSH Configuration: $(cat /etc/ssh/sshd_config)"
echo "System Logs: $(tail -n 10 /var/log/syslog)"
echo "Recent Authentication Logs: $(tail -n 10 /var/log/auth.log)"
echo "Recent Kernel Logs: $(dmesg | tail -n 10)"
echo "Recent Application Logs: $(tail -n 10 /var/log/apache2/error.log)"
echo "Environment Variables Count: $(printenv | wc -l)"
echo "All Arguments in a Single String: $*"